### ISSUE TITLE
[Crash] Crsh when im entering village

### ISSUE THREAD

**Issue by Taknax** [SuperMartijn642/Wormhole#11]
**Version Info**
- Minecraft, 1.12.2
- Wormhole, 1.1.3

**Its in combi with my modpack and arrived till i have Blue Power mod installed. I tried without Blue Power and the issue arrived. Also its not because Blue Power.**
...

**Crash report (~/logs/latest.log)**

[https://pastebin.com/sk2qN6KP](url)

**Comment by SuperMartijn642** [comment]
I fixed it now in version 1.1.4.

Thanks for reporting the issue!
