### ISSUE TITLE
[Crash] on startup after updating

### ISSUE THREAD

**Issue by Staegrin** [SuperMartijn642/Wormhole#14]
**Version Info**
- Minecraft, ...
1.16.5 forge 36.0.48
- Wormhole, ...
wormhole-1.1.5-mc1.16.3
**Steps to Reproduce**
updated and then it will crash

**Crash report (~/logs/latest.log)**
crashlog https://gist.github.com/Staegrin/044e1ce2957d31103d558ac35a3f6888
log https://gist.github.com/Staegrin/00975267b8d6c3c91e8507656675ef9a

**Comment by SuperMartijn642** [comment]
As it says, you need [Core Lib](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib).

**Comment by Staegrin** [comment]
tried it with both 
supermartijn642configlib-1.0.5a-mc1.16
and 
supermartijn642corelib-1.0.0-mc1.16.5 (the latest version according to curseforge)
with 1.0.0
log https://gist.github.com/Staegrin/18759b452de9b68f158c6a8f6856c4d9
crashlog on start https://gist.github.com/Staegrin/cdd479af0e2a459f60e565b53ff2895f

with 1.0.5a
log https://gist.github.com/Staegrin/3444d76e130346a96b7505d1eebeb647
crashlog https://gist.github.com/Staegrin/9fe899d697320c9e009d31d0ac120a4a

both versions of core lib have a crash at the start. Downgrading wormhole to version wormhole-1.1.4-mc1.16.3 does not cause a crash. So I think the problem is with the wormhole update. Not the core lib.

**Comment by SuperMartijn642** [comment]
Hmm, interesting

**Comment by SuperMartijn642** [comment]
Note that Config Lib and Core Lib are separate mods. Wormhole only requires Core Lib.
It seems you also have Chunk Loaders which requires Config Lib, so you need both.

**Comment by Staegrin** [comment]
Yes, because the previous version of wormhole didn't require a lib mod I was getting the core lib and the config lib mixed up. Both are needed in the modpack because it contains various mods by you. Thank you for your help and your amazing mods.

PS one thing to mention on the curseforge page for wormhole file wormhole-1.1.5-mc1.16.5 leads to downloading file wormhole-1.1.5-mc1.16.3.jar while the other downloads the name and the download matches.

**Comment by SuperMartijn642** [comment]
Glad it works now!

> PS one thing to mention on the curseforge page for wormhole file wormhole-1.1.5-mc1.16.5 leads to downloading file wormhole-1.1.5-mc1.16.3.jar while the other downloads the name and the download matches.

That is weird, I uploaded a file called 1.1.5-mc1.16.3.jar and then changed the display name to 1.16.5. Bit annoying, but I guess now I know to change the name before uploading it.
