### ISSUE TITLE
[Bug] Nether and End traveling

### ISSUE THREAD

**Issue by bloksskywalker** [SuperMartijn642/Wormhole#15]
Version 1.16.3
Minecraft Forge
Wormhole

Everything worked well and I really liked it... Until I tried using it inter-dimensionally. I don't know if it forgets to convert the overworld chords to nether/end chords or it just doesn't capture the chords right, but whenever I go to the nether or the end I get teleported to a seemingly random spot. I thought it was random until I used it more times and it kept putting me in the same "random" spot

To reproduce this just build a nether/end portal, go in once and take chords on the Advanced or normal target definition device, go back to the overworld, transfer the chords to the wormhole and walk in. If you go back to the overworld and try again it will teleport you to the same wrong location.

**Screenshots**
...

**Comment by SuperMartijn642** [comment]
What version of Wormhole are you using?

**Comment by bloksskywalker** [comment]
1.1.15 wormhole version for 1.16.2 Minecraft version

**Comment by SuperMartijn642** [comment]
I assume you meant Wormhole version 1.1.5.

I did fix an issue an version 1.1.6 now, with other entities not being teleported between dimensions.
However, for players it already seems to work just fine.

Is there anything else needed to reproduce the issue?

**Comment by bloksskywalker** [comment]
This is probably just an issue on my end but I can't open the new version. I can't try it on the new version so I will just mark this as closed.
