### ISSUE TITLE
[Question] ...Has configlib been superseded by corelib

### ISSUE THREAD

**Issue by IamStig** [SuperMartijn642/Wormhole#16]
**Question**
...Has configlib been superseded by corelib, to run Wormhole do I need both?
Does it break a game if both corelib and configlib are included?
I don't recall if configlib was a "required dependency" for Wormhole previously but I don't know why it would be needed otherwise.

**Comment by SuperMartijn642** [comment]
For now, Config Lib and Core Lib are two separate mods without any overlap. Wormhole only requires Core Lib.

I kinda messed up by releasing Config Lib as a standalone mod, while it should have probably been part of Core Lib.
Oh well, now Core Lib should be the last library mod which will just contain everything I need, and Config Lib will just remain as is.

**Comment by IamStig** [comment]
OK, **it happens! So I guess the best option is to keep both in this pack (DW20) I am playing, just in case, and in future packs I only need have installed core lib and Wormhole.
Thanks for fast reply BTW

**Comment by SuperMartijn642** [comment]
I think the DW20 pack also has Simple Magnets which does require Config Lib.
But yes, for Wormhole it is only Wormhole and Core Lib.

**Comment by IamStig** [comment]
It does have Simple Magnets. Thanks again
