### ISSUE TITLE
[Feature] Allow portals to work underwater

### ISSUE THREAD

**Issue by Demolishun** [SuperMartijn642/Wormhole#17]
**Is your feature request related to a problem? Please describe.**
I would like to be able to transport marine life that swims through the water into a fish tank.

**Describe the solution you'd like**
Please allow portal formation to occur if water is inside the portal.

**Comment by Demolishun** [comment]
As a work around I used Cyclic fans on the ocean floor to push fish up into a portal just above the water.

**Comment by SuperMartijn642** [comment]
Portal can now be waterlogged in version 1.1.11.

Thank you for the suggestion!
