### ISSUE TITLE
[Bug] Going through portal on horse desync

### ISSUE THREAD

**Issue by MichelJonkman** [SuperMartijn642/Wormhole#19]
**Version Info**
- Minecraft, 1.16.5
- Wormhole, 1.1.7

**Description of the Bug**
Going through a portal on a horse sometimes causes a desync.

**Steps to Reproduce**
The best way I've found to reproduce is to build 2 portals but it also happens with one (And very often with the ultimate car mod).

- Designate point 1 one block in front of portal 1.
- Set portal 2 to point 1.
- Set portal 1 to something else, doesn't really matter, it just needs to be activated.
- Go through portal 2 in the direction that would make you go through portal 1 if you go straight.
- This causes me to desync, server says that client is still on the horse while the client looks like it isn't.

I could provide a video if it's not clear.

**Comment by SuperMartijn642** [comment]
I fixed it now in version 1.1.8.

Thanks for reporting the issue!
