### ISSUE TITLE
[Crash] Encountered an error

### ISSUE THREAD

**Issue by Baggytrousers27** [SuperMartijn642/Wormhole#21]
supermartijn642configlib-1.0.9-mc1.17
supermartijn642corelib-1.0.12-mc1.17
Wormhole 1.1.8 mc1.17
Forge 17.17.1-37.0.31(33)

Wormhole (Portals) (wormhole) encountered an error during the common_setup event phase

java.lang.NoSuchMethodError: 'net.minecraft.world.level.clock.stat.BlockBehaviour$Properties

Wormhole (Portals) (wormhole) encountered an error during the error event phase

Java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Block.getRegistryName()" because

Wormhole (Portals) (wormhole) encountered an error during the error event phase

java.lang.NullPointerException: null

[Crashlog](https://pastebin.com/guEdis2v)

**Comment by SuperMartijn642** [comment]
I fixed it now in Wormhole version 1.1.8a.

Thank you for reporting the issue!
