### ISSUE TITLE
[Bug] Going through end portal breaks Wormhole's portals

### ISSUE THREAD

**Issue by Elvundil** [SuperMartijn642/Wormhole#22]
**Version Info**
- Minecraft, ... 1.16
- Wormhole, ... 1.1.8

**Description of the Bug**

when you pass a portal for the end and you come back via the portal of the end (the one generated after killing the dragon) you have to break the portal stabilizer otherwise the portal no longer works.

**Steps to Reproduce**
just passed the gate and come back.

**Comment by SuperMartijn642** [comment]
Ah I had a situation just like this on a playthrough and just could not figure out what had caused the portal to break, this was probably it.
I don't know when I'll have time to look into it and fix it, so it might take a bit.

**Comment by SuperMartijn642** [comment]
I fixed it now in Wormhole version 1.1.9.

Thank you for reporting the issue!
