### ISSUE TITLE
[Crash] Integrated Server Crash when placing an Energy Cell ontop of a Immersive Engineering Garden Cloche. (maybe more items that accept power).

### ISSUE THREAD

**Issue by Gbergz** [SuperMartijn642/Wormhole#24]
**Version Info**
- Minecraft, 1.18.1
- Forge, 39.0.56
- Wormhole, 1.1.9a | https://www.curseforge.com/minecraft/mc-mods/wormhole-portals/files/3594311

**Steps to Reproduce**
Place Energy Cell ontop of the Garden Cloche, right-click the Cloche.
Crash.

**Crash report 1**
https://gist.github.com/Gbergz/e2f575fa4e7fe6f639dae342248f448d

**Crash report 2**
https://gist.github.com/Gbergz/12c3bf9f6d1e74bf6738771792e96aaf

**Comment by SuperMartijn642** [comment]
I fixed it now in Wormhole 1.1.9b for Minecraft 1.18.

Thank you for reporting the issue!
