### ISSUE TITLE
[Feature] Let us name portals in their UI

### ISSUE THREAD

**Issue by vizthex123** [SuperMartijn642/Wormhole#27]
**Is your feature request related to a problem? Please describe.**
Sort of

**Describe the solution you'd like**
It'd be nice if we could name portals in their UI, and/or naming the stabilizer in an anvil. Would make it a lot easier to organize things.

I play the 1.18.2 version of the mod, so it'd be cool to have it there (or even on every version)

**Comment by SuperMartijn642** [comment]
What would naming a portal do? Where would you see this name?

**Comment by vizthex123** [comment]
Lets you organize them better....?

And it could just replace the "portal overview" text.

**Comment by SuperMartijn642** [comment]
So you want to be able to give a portal a name just to see it in its own portal overview screen?
How does that let you organize them better?

**Comment by vizthex123** [comment]
i just like being able to name things tbh, lets me find stuff easier - especially when testing mods, which i do in a pretty small area.

**Comment by SuperMartijn642** [comment]
I will not be adding this as I don't see the use in it.
