### ISSUE TITLE
[Bug] Config doesn't save changes

### ISSUE THREAD

**Issue by vizthex123** [SuperMartijn642/Wormhole#29]
**Version Info**
- Minecraft: 1.18.2
- Wormhole: 1.1.9b

**Description of the Bug**
Whenever I edit the config, it doesn't save when I load the game again. It just reverts to the defaults.

**Steps to Reproduce**
1) Edit the config
2) Load the game

**Screenshots**:
Not applicable. Here's the game log
[latest.log](https://github.com/SuperMartijn642/Wormhole/files/8934140/latest.log)

**Comment by SuperMartijn642** [comment]
It is fixed now in version 1.1.4 of my config lib.
Thank you for reporting the issue!

**Comment by vizthex123** [comment]
thanks for fixing it!
