### ISSUE TITLE
[Crash] Crash when a generator goes empty in a spawn chunk while the player is far away in a server

### ISSUE THREAD

**Issue by antoine-lombardo** [SuperMartijn642/Wormhole#34]
**Version Info**
- Minecraft, 1.19.2
- Forge 43.1.7
- Wormhole, 1.1.10b
- Core Lib, 1.0.19a
- Config Library 1.1.6b

**Steps to Reproduce**
IN A SERVER: Create a portal at spawn with only one wooden plank in the genrator, go through it (far away from the spawn chunks), wait for the generator to go empty and you game should crash. I think it has something to do with the fact that the player do not have the spawn chunks loaded, so it thinks that the coal generator is an empty block.

**Error thrown**
Error: java.lang.IllegalArgumentException: Cannot set property BooleanProperty{name=lit, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:void_air}

**Crash report (~/logs/latest.log)**
https://gist.github.com/antoine-lombardo/6146d5966f57e8af7a25f6d5f7c07aac

**Comment by SuperMartijn642** [comment]
Thank you for the report. Does the issue occur with just Wormhole installed?

Also, could you upload the logs through something like https://gist.github.com/ and send the link from that? It makes it a bit easier to read 😅

**Comment by antoine-lombardo** [comment]
Sorry about that, I have put it here: https://gist.github.com/antoine-lombardo/6146d5966f57e8af7a25f6d5f7c07aac

I tried with no other mods installed, and I cannot reproduce the error, I will try again one mod at a time to see which one cause it.

Thanks!

**Comment by SuperMartijn642** [comment]
From what I can see in the crash log, FreeCam by Zergatul, OptiFine, Xaero's Minimap, and Xaero's World Map seem to apply mixins to some of the classes involved in the crash, so one of them would be my first guess for causing the issue.
I don't think OptiFine, Xaero's Minimap, or Xaero's World Map would cause these kinds of issues though, so maybe it's FreeCam by Zergatul.

Thanks for looking into it and let me know what you find 🙂

**Comment by SuperMartijn642** [comment]
Closing this as version 1.1.11 redoes most of the code related to this anyways. If the crash still occurs, please open a new issue with updated logs.
