### ISSUE TITLE
[Crash] v1.1.11 crashes when running on a server

### ISSUE THREAD

**Issue by JulianVennen** [SuperMartijn642/Wormhole#36]
**Version Info**
- Minecraft, 1.12.2
- Wormhole, 1.1.11

**Steps to Reproduce**
- install the mod and its dependencies on a forge server
- attempt to start the server

**Crash report (~/logs/latest.log)**
Log: https://mclo.gs/GMS3ACq
Crash Report: https://mclo.gs/iExuGw4

This issue doesn't exist in v1.1.10

**Comment by SuperMartijn642** [comment]
Fixed now in version 1.1.11a for Minecraft 1.12.

Thank you for reporting the issue!
