### ISSUE TITLE
[Crash] 1.19.4 NBT Filter Error

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SuperMartijn642/Wormhole#39]
**Version Info**
- Minecraft, 1.19.4 - 45.0.27
- Wormhole, wormhole-1.1.12-forge-mc1.19.3

**Crash report (~/logs/latest.log)**
[...](https://gist.github.com/P3rf3ctXZer0/6e770b538fc9e831f78588d2dd963b8c)

**Comment by SuperMartijn642** [comment]
Should work with the dedicated file for 1.19.4 for now.
Thank you for reporting the issue!
