### ISSUE TITLE
Can't use portals until I die once

### ISSUE THREAD

**Issue by Arzanor** [SuperMartijn642/Wormhole#4]
When I join my server I can't use wormhole portals until I die, after there isn't any problem at all but it's really anoying to have to die every time I join the server...

Before dying I can create portals and other players can pass through, but not me. I tried to break them, change the location, change the shape, etc. The only thing fixing the bug is my death.

It's the same for all the players, not just me.

(I'm using wormhole-1.0.7-mc1.16.2 on 1.16.2 server)

**Comment by SuperMartijn642** [comment]
I can't replicate your issue, however I did find a bug where you can't enter the portal after dying instead of before dying.
Could you see if version 1.0.8 happens to fix your issue too?

**Comment by Arzanor** [comment]
Yes it's working perfectly now !
It's a little weird that it's the other way around for me, but it's working, so everything is fine :)

Thank you for your help
I really love your mod :)

**Comment by SuperMartijn642** [comment]
Well I'm glad that fixed it. 😄

Thanks for reporting the issue!
