### ISSUE TITLE
[Crash] Fabric version crashes on startup

### ISSUE THREAD

**Issue by SplendidAlakey** [SuperMartijn642/Wormhole#40]
**Version Info**
- Minecraft, 1.19.4
- Wormhole, 1.1.12

**Steps to Reproduce**
Simply install the mod and its dependencies, then run the game.

**Crash report (~/logs/latest.log)**
https://gist.github.com/SplendidAlakey/1fc44ecb285a6a6d6bc5f2610e235e8d

**Comment by SuperMartijn642** [comment]
I fixed it now in Wormhole version 1.1.12a.

Thank you for reporting the issue!
