### ISSUE TITLE
[Crash] Prevent server to start

### ISSUE THREAD

**Issue by Lulaley** [SuperMartijn642/Wormhole#41]
**Version Info**
- I'm using minecraft 1.18.2 with fabric-0.14.19
- Wormhole (wormhole-1.1.12-fabric-mc1.18.jar) is one of the mod using in my modpack. I'm also using :
       * Ad Astra
       * Advanced Netherite
       * Advanced Reborn
       * Advancement Plaques
       * AdventureZ
       * AE2 Things
       * Amplified Nether
       * AppleSkin
       * Applied Botanics Addon
       * Applied Energistics 2
       * Applied Energistics 2 Wireless Terminals
       * Architectury API
       * Auth Me
       * Auto Config Updated API
       * BCLib
       * Better Advancements
       * Better Third Person
       * BetterEnd
       * BetterNether
       * Bewitchment
       * Bewitchment Plus
       * Bookshelf
       * Botania
       * Botany Pots
       * Cardinal Components
       * Charm
       * Chassis
       * Chat Heads
       * Chipped
       * Chisel Refabricated
       * Cloth Config API
       * Clumps
       * Comforts
       *  Compact Machines
       * Compressor
       * Continuity
       * Controlling
       * Crafting Tweaks
       * Create Crafts & Additions
       * Create Fabric
       * CreatePlus
       * CreativeCore
       * Creatures From The Snow
       * Creeper Firework
       * Creeper Overhaul
       * Croptopia
       * CTM Refabricated
       * Cultural Delights
       * Custom Machinery
       * Dank Storage Fabric
       * Dark Utilities
       * Dawn API
       * Decorative Blocks
       * Disenchanter
       * DragonLoot
       * Duckling
       * Dynamic Asset Generator
       * Ecologics
       * Enchantment Descriptions
       * EnderChests
       * Enderite Mod
       * Enderite Reinforced Storage
       * Entangled
       * Excavated Variants
       * Expanded Delight
       * Extended Drawers
       * Extractinator
       * Extreme sound muffler
       * Fabric API
       * Fabric Language Kotlin
       * Factory Blocks
       * Falling Leaves
       * Farmer's Delight
       * Farmer's Knives
       * Feature NBT Deadlock Be Gone
       * FerriteCore
       * Forge Config API Port
       * FTB Chunks
       * FTB Library
       * FTB Quests
       * FTB Teams
       * FTB Ultimine
       * Galosphere
       * GeckoLib
       * Health Overlay
       * Hephaestus Fabric
       * Hex Casting
       * Iceberg
       * Incendium
       * Indium
       * Industrial Revolution
       * Iron Jetpacks Fabric
       * Item Collectors
       * Item Filters
       * Item Highlighter
       * ItemPhysic Lite
       * Jade
       * JamLib
       * JourneyMap
       * JourneyMap Integration
       * KubeJS
       * LambDynamicLights
       * Legendary Tooltips
       * Lootr
       * Lychee
       * MCPitanLib
       * ME Requester
       * MemoryLeakFix
       * Mining Dimensions
       * MmmMmmMmmMmm
       * Mod Menu
       * More Villagers
       * Mouse Tweaks
       * Naturalist
       * Nature's Compass
       * Nether's Delight
       * NPC Variety - Port
       * spriir
       * OpenBlocks Elevator
       * Paradise Lost
       * Patchouli
       * PAUCAL
       * Pehkui
       * Per Aspera
       * Pig Pen Cipher
       * Polymorph
       * Ponder for KubeJS
       * Portal Cubed
       * Powah!
       * Prism
       * Quarry Reborn
       * Reborn Core
       * Reinforced Barrels
       * Reinforced Chests
       * Reinforced Shulker Boxes
       * Resourceful Lootbags
       * Rhino
       * RightClickHarvest
       * Rotten Creatures
       * Roughly Enough Items
       * Roughly Enough Loot Tables
       * Roughly Enough Professions
       * Runelic
       * Scannable
       * ShetiPhianCore
       * ShulkerBoxTooltip
       * Simple Magnets
       * Simple Void World
       * Spirit
       * Staff of Traveling
       * Structory
       * Subterrestrial
       * SuperMartijn642's Config Lib
       * SuperMartijn642's Core Lib
       * Tech Reborn
       * Tempad
       * TerraBlender
       * The Bumblezone
       * The Wild Backport
       * Time in a Bottle
       * Towns and Towers
       * Trade Cycling
       * Trash Cans
       * Trinkets
       * Twigs
       * VoidZ
       * Waystones
       * Wired Redstone
       * World Stripper
       * Wormhole (Portals)
       * YUNG's API
       * YUNG's Better Nether Fortresses
       * YUNG's Better Strongholds
I'm runing my server on UNIX (Mint) with an java JDK  1.18.

**Steps to Reproduce**
Just start a server instance

**Crash report (~/logs/latest.log)**
First log : https://pastebin.com/X8dnVEav
Password for first log : Uj6jGSgQmJ
Second log : https://pastebin.com/LQMkXx39
Password for second log : sQGEecQUa1

**Comment by SuperMartijn642** [comment]
Please update to version 1.1.12a.

**Comment by Lulaley** [comment]
I have made two crash report cause i have test in :
1.1.12
ans
1.1.12a

**Comment by SuperMartijn642** [comment]
The second crash seems unrelated to Wormhole as far as I can tell.
> Could not execute entrypoint stage 'server' due to errors, provided by 'midnightlib'!

**Comment by Lulaley** [comment]
Okay !
Tanks for your fast respons !
nd sorry for this disagreement !
