### ISSUE TITLE
[Bug] Cave Air and Void Air Prevent Portal Contruction

### ISSUE THREAD

**Issue by MizzyMizi** [SuperMartijn642/Wormhole#46]
**Version Info**
- Minecraft, 1.16.5
- Wormhole, 1.1.12

**Description of the Bug**
cave_air and presumably void_air prevent portals from being valid.

**Steps to Reproduce**
build a portal within a cave or fill a portal with cave_air or void_air.

**Comment by SuperMartijn642** [comment]
Fixed now in version 1.1.13 of Wormhole.
Thank you for reporting the issue!
