### ISSUE TITLE
[Bug] ...

### ISSUE THREAD

**Issue by ZenithTheWolf** [SuperMartijn642/Wormhole#48]
Version Info:
- Minecraft, 1.12.2
- Wormhole, 1.1.12
- SuperMartijn642's Core Lib, 1.1.10
- SuperMartijn642's Config Lib, 1.1.6
(PNG of my full mod list below)

Whenever I install any version of Wormhole (I tried every version back to 1.1.9), certain textures bug out considerably. From what I can tell, it's at least the Thermal Dynamics pipes, Futura Blocks, and every Portal Gun's textures. I have a suspicion one or more of these mods are incompatible with Wormhole altogether; which would be unfortunate, because there doesn't seem to be many good portal mod options for my personal 1.12.2 modpack. I'm looking for something that can get me to and from the end interdimensionally, and it appears this seems to be my best bet. (Meecreeps' portal gun doesn't work and the regular Portal Gun can't travel interdimensionally)
I imagine you won't be able to help me much if this is indeed an incompatibility, but I'd at least like to know what someone who knows what they're talking about thinks.
...

Install Wormhole version 1.1.9 - 1.1.12 alongside my modlist, bring out the objects in question and and see their textures break.

Screenshots:
My Modlist:
![Screenshot (41)](https://github.com/SuperMartijn642/Wormhole/assets/18382061/55dd3168-df5d-4d4d-ba81-5c578dd100e4)
...
Thermal Dynamic's Pipe Break:
![Thermal Dynamic's Pipe break](https://github.com/SuperMartijn642/Wormhole/assets/18382061/2ee4cc8b-babb-4eb6-b0ca-0ff197ee37e0)
...
Futura Block Break:
![Futura Block Break](https://github.com/SuperMartijn642/Wormhole/assets/18382061/a26075af-4e2e-4ad2-a56c-a3704edf5ea1)

**Comment by SuperMartijn642** [comment]
I strongly doubt this is caused by Wormhole. Wormhole does nothing related to models or textures. It just uses vanilla models.

That mod list seems way too large to do anything with. Could you narrow down the mods needed to reproduce the issue?

**Comment by ZenithTheWolf** [comment]
That could probably take hours if not days with my mod list and how long it takes Minecraft to launch. So if you agree that it's most likely not a Wormhole problem, then it must be one of my other 180+ mods interacting with it.
Regardless, I managed to get the MeeCreeps portal gun to work, so I no longer absolutely require a mod to make custom portals. It'd be nice, but well... gotta pick my battles, y'know?

Go ahead and close this thread; sorry for wasting your time.
