### ISSUE TITLE
[Feature] Allow Coal Generators to have coal be auto-input, or portals to accept power cables - Fabric

### ISSUE THREAD

**Issue by LokeYourC3PH** [SuperMartijn642/Wormhole#49]
**Is your feature request related to a problem? Please describe.**
Indeed it is. Portals do not accept cables from Tech Reborn, Industrial Revolution, AE2, or anything in terms of power. Coal Generators are the only thing that can generate power for portals, which is truly quite frustrating. However, Coal Generators ALSO don't accept auto-input of Coal, making ANY sort of automation impossible.

**Describe the solution you'd like**
For the above issue to be solved somehow. Either accepting power, or accepting auto-input of coal.

MC Version: 1.20.1
Modloader: Fabric

**Comment by SuperMartijn642** [comment]
Both of those should work, so probably just something I messed up then.

**Comment by LokeYourC3PH** [comment]
![2023-07-21_23 54 51](https://github.com/SuperMartijn642/Wormhole/assets/5807595/b210e1d1-703e-4491-acef-3b8852d10c85)

As you can see, cables do not connect, item pipes don't either, and AE/ME Export bus' do not function either. Using the latest version of the mod on Fabric 1.20.1 :)

EDIT: Oh and I even tried Hoppers for auto inserting coal, doesn't work either.

**Comment by SuperMartijn642** [comment]
Energy cables from Tech Reborn seem to connect as you would expect
![image](https://github.com/SuperMartijn642/Wormhole/assets/12382965/1e1cbe69-52c1-4cdc-8a2f-fd9e51ded830)

What version of Wormholes are you using?

**Comment by LokeYourC3PH** [comment]
> Energy cables from Tech Reborn seem to connect as you would expect ![image](https://user-images.githubusercontent.com/12382965/255220719-1e1cbe69-52c1-4cdc-8a2f-fd9e51ded830.png)
> 
> What version of Wormholes are you using?

I'm a dumbass, apparently I am for some reason using version 1.1.12 instead of 1.1.13 on the server. RIP my stupid ass.
