### ISSUE TITLE
[Crash] Crash when hovering over 

### ISSUE THREAD

**Issue by yeboiTeki** [SuperMartijn642/Wormhole#50]
**Version Info**
- Minecraft, 1.20.1 (Forge with Optifine)
- Wormhole, 1.1.12 

**Steps to Reproduce**
Hover over Interface Element like the Battery Gauge on the Coal Generator, Crashes instantly.

**Crash report (~/logs/latest.log)**
[latest2.txt](https://github.com/SuperMartijn642/Wormhole/files/12315324/latest2.txt)
[latest.log](https://github.com/SuperMartijn642/Wormhole/files/12315325/latest.log)

**Comment by SuperMartijn642** [comment]
Seems like it might be caused by Iceberg.

**Comment by SuperMartijn642** [comment]
As discussed on Discord, it was caused by a combination of Iceberg and OptiFine and fixed by updating Iceberg.

The issue seems unrelated to Wormhole and I'll close the issue.
