### ISSUE TITLE
[Bug] Incorrect Teleport Cost

### ISSUE THREAD

**Issue by OliverWolf621** [SuperMartijn642/Wormhole#51]
**Version Info**
- Minecraft, 1.18.2
- Wormhole, 1.1.13
- Forge 40.2.10

**Description of the Bug**
Teleport cost does not change with distance, stuck at 500. Configs are all default, on a new installation. Nothing in latest or debug log

**Steps to Reproduce**
Unsure, I had made a new installation on the CurseForge app, installed the mod and it's 2 dependencies, opened the game and immediately made a new world, built a portal and set the destination literally 4 blocks away and the cost read 500. Tried somethere else, still 500...

**Screenshots**
...
![2023-08-16_20 47 31](https://github.com/SuperMartijn642/Wormhole/assets/142481537/4be64111-19b8-4f4a-a76c-e2565908e0be)

**Comment by SuperMartijn642** [comment]
Seems it was always taking the cross-dimension teleport cost. It is fixed now in version 1.1.13a for Forge and 1.1.13b for Fabric.
Thank you for reporting the issue!
