### ISSUE TITLE
[Bug] config sizePowerDrain and distancePowerDrain values reset to default after game restart / aren't being read properly

### ISSUE THREAD

**Issue by OliverWolf621** [SuperMartijn642/Wormhole#52]
**Version Info**
- Minecraft, 1.18.2
- Wormhole, 1.1.13a

**Description of the Bug**
Changed the config file to adjust sizePowerDrain and distancePowerDrain, but upon restarting the game, they both reset to 0.5 (default). Changing it with the game open to the main menu then loading a world, the mod doesn't seem to read the values, as the energy costs aren't changed. Values other than sizePowerDrain and distancePowerDrain seem to work fine.

**Steps to Reproduce**
Open the mods config and change sizePowerDrain and distancePowerDrain to a different value. Save then close the file. Launch or restart your game and load into a world, the teleport cost will be unchanged. Reopen the config file and both sizePowerDrain and distancePowerDrain values will be reset to 0.5.
If you change the config with the game open then load a world without restarting your game, the config will not change, but energy costs will not change, like the mod isnt reading those values. Restarting your game then resets the sizePowerDrain and distancePowerDrain values in the config.

**Screenshots**
...
<img width="428" alt="yay" src="https://github.com/SuperMartijn642/Wormhole/assets/142481537/e80cd544-249b-40be-97dd-5f241fabf869">
<img width="960" alt="yayyy" src="https://github.com/SuperMartijn642/Wormhole/assets/142481537/68c4ced4-3759-4c5b-8382-aa28e912d06c">

**Comment by SuperMartijn642** [comment]
Seems this is caused by my config library. The double config entry doesn't accept `10`, but does accept `10.0`, since `10` gets read as an integer.
I fixed it now in version 1.1.8 of my config library.
Thank you for reporting the issue!
