### ISSUE TITLE
Nether Portals being created around Wormhole portals.

### ISSUE THREAD

**Issue by knoxhack** [SuperMartijn642/Wormhole#9]
I have multiple players telling of random nether portals appearing around the around where they have Wormhole portals. Do you guys know anything about and how would the mod interfere with nether portals?
This is really bad for my modpack because the nether was supposed to be disable on this modpack. Thanks a lot if any reply.

**Comment by knoxhack** [comment]
This is using Minecraft Forge 1.12.2

**Comment by SuperMartijn642** [comment]
Seems to be specific to 1.12, but I fixed it now in version 1.0.9a.

Thanks for the report!

**Comment by knoxhack** [comment]
I forgot to mention this was on a server. But it should be fixed on servers too right?

**Comment by SuperMartijn642** [comment]
Yes indeed
